"""FP Taxonomy Engine: Deterministic candidate finding rejection taxonomy (E12-3, E12-10)."""

from enum import StrEnum


class FPTaxonomyReason(StrEnum):
    """Explicit, deterministic reasons for rejecting candidate findings.

    Every candidate finding that fails qualification must have an explicit reason.
    Silently dropping candidate findings is prohibited.
    """

    LEXICAL_ONLY = "LEXICAL_ONLY"
    COMMENT_OR_STRING_MATCH = "COMMENT_OR_STRING_MATCH"
    UNCONSTRAINED_SINK = "UNCONSTRAINED_SINK"
    UNTAINTED_INPUT = "UNTAINTED_INPUT"
    STATIC_INPUT = "STATIC_INPUT"
    SANITIZED_INPUT = "SANITIZED_INPUT"
    INCOMPATIBLE_SANITIZER = "INCOMPATIBLE_SANITIZER"
    INVALID_SINK_CONTEXT = "INVALID_SINK_CONTEXT"
    NON_EXECUTING_OPERATION = "NON_EXECUTING_OPERATION"
    PARAMETER_BINDING = "PARAMETER_BINDING"
    SAFE_PREPARATION = "SAFE_PREPARATION"
    WRONG_SINK_CATEGORY = "WRONG_SINK_CATEGORY"
    WRONG_SANITIZER = "WRONG_SANITIZER"
    WRONG_RULE_SCOPE = "WRONG_RULE_SCOPE"
    DUPLICATE_SEMANTIC_FINDING = "DUPLICATE_SEMANTIC_FINDING"
    DUPLICATE_SEMANTIC_EVIDENCE = "DUPLICATE_SEMANTIC_EVIDENCE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNKNOWN_FLOW = "UNKNOWN_FLOW"
