"""FindingCollection model with sorting, minimum severity filtering, and rule/file grouping abstractions."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple
from karsasec.core.finding.model import Finding
from karsasec.rules.enums import Severity

SEVERITY_WEIGHTS: Dict[Severity, int] = {
    Severity.CRITICAL: 5,
    Severity.HIGH: 4,
    Severity.MEDIUM: 3,
    Severity.LOW: 2,
    Severity.INFO: 1,
}

@dataclass(frozen=True)
class FindingCollection:
    """Immutable collection wrapping Finding objects with filtering, sorting, and grouping abstractions."""

    findings: Tuple[Finding, ...] = field(default_factory=tuple)

    @property
    def total(self) -> int:
        """Returns total number of findings in collection."""
        return len(self.findings)

    @property
    def severity_summary(self) -> Dict[Severity, int]:
        """Calculates counts per Severity level."""
        summary: Dict[Severity, int] = {sev: 0 for sev in Severity}
        for finding in self.findings:
            summary[finding.severity] = summary.get(finding.severity, 0) + 1
        return summary

    def by_severity(self, severity: Severity) -> Tuple[Finding, ...]:
        """Returns findings matching the exact Severity."""
        return tuple(f for f in self.findings if f.severity == severity)

    def by_file(self, file_path: Path) -> Tuple[Finding, ...]:
        """Returns findings associated with a specific file path."""
        norm = str(file_path).replace("\\", "/")
        return tuple(f for f in self.findings if str(f.file_path).replace("\\", "/") == norm)

    def by_rule(self, rule_id: str) -> Tuple[Finding, ...]:
        """Returns findings generated by a specific rule_id."""
        return tuple(f for f in self.findings if f.rule_id == rule_id)

    def sort_by_severity(self, descending: bool = True) -> "FindingCollection":
        """Returns a new FindingCollection sorted by Severity weight."""
        sorted_list = sorted(
            self.findings,
            key=lambda f: SEVERITY_WEIGHTS.get(f.severity, 0),
            reverse=descending,
        )
        return FindingCollection(findings=tuple(sorted_list))

    def filter_by_min_severity(self, min_severity: Severity) -> "FindingCollection":
        """Returns a new FindingCollection containing findings at or above min_severity."""
        min_weight = SEVERITY_WEIGHTS.get(min_severity, 0)
        filtered = [f for f in self.findings if SEVERITY_WEIGHTS.get(f.severity, 0) >= min_weight]
        return FindingCollection(findings=tuple(filtered))

    def group_by_rule(self) -> Dict[str, Tuple[Finding, ...]]:
        """Groups findings by rule_id."""
        grouped: Dict[str, List[Finding]] = {}
        for f in self.findings:
            if f.rule_id not in grouped:
                grouped[f.rule_id] = []
            grouped[f.rule_id].append(f)
        return {rule_id: tuple(items) for rule_id, items in grouped.items()}

    def group_by_file(self) -> Dict[Path, Tuple[Finding, ...]]:
        """Groups findings by file_path."""
        grouped: Dict[Path, List[Finding]] = {}
        for f in self.findings:
            if f.file_path not in grouped:
                grouped[f.file_path] = []
            grouped[f.file_path].append(f)
        return {path: tuple(items) for path, items in grouped.items()}
