"""initial_schema

Revision ID: 16e35b77308a
Revises: 
Create Date: 2026-08-13 23:11:13.856959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e35b77308a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=256), nullable=False),
    sa.Column('rule_id', sa.String(length=256), nullable=False),
    sa.Column('receipt_version', sa.String(length=16), nullable=False),
    sa.Column('integrity_status', sa.String(length=32), nullable=False),
    sa.Column('security_verification_status', sa.String(length=64), nullable=False),
    sa.Column('verification_run_id', sa.String(length=256), nullable=True),
    sa.Column('matching_findings_count', sa.Integer(), nullable=False),
    sa.Column('proposal_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('provenance_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ledger_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('receipt_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_fingerprint'),
    sa.UniqueConstraint('receipt_fingerprint', name='uq_receipts_fingerprint')
    )
    op.create_index(op.f('ix_receipts_receipt_id'), 'receipts', ['receipt_id'], unique=True)
    op.create_index(op.f('ix_receipts_transaction_id'), 'receipts', ['transaction_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('finding_id', sa.String(length=256), nullable=False),
    sa.Column('approval_token_id', sa.String(length=256), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_seconds', sa.Integer(), nullable=False),
    sa.Column('lease_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('receipt_id', sa.String(length=128), nullable=True),
    sa.Column('receipt_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('security_verification_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_fingerprint'), 'tasks', ['fingerprint'], unique=False)
    op.create_index('ix_tasks_state_fingerprint', 'tasks', ['state', 'fingerprint'], unique=False)
    op.create_index('ix_tasks_state_lease', 'tasks', ['state', 'lease_started_at'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_task_created', 'audit_events', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_task_id'), 'audit_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_task_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_task_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index('ix_tasks_state_lease', table_name='tasks')
    op.drop_index('ix_tasks_state_fingerprint', table_name='tasks')
    op.drop_index(op.f('ix_tasks_fingerprint'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_receipts_transaction_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
