"""Query AST Data Models and Serialization for CPG Query Engine."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class StepType(str, Enum):
    """Step types in CPG Query AST."""

    SELECT = "SELECT"
    WHERE = "WHERE"
    TRAVERSE = "TRAVERSE"
    FILTER = "FILTER"
    LIMIT = "LIMIT"
    RETURN = "RETURN"
    PROJECT = "PROJECT"
    ORDER_BY = "ORDER_BY"


@dataclass(frozen=True)
class PredicateNode:
    """Immutable Predicate AST node."""

    operator: str
    target: str
    value: Any = None
    args: tuple[PredicateNode, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "operator": self.operator,
            "target": self.target,
            "value": self.value,
            "args": [a.to_dict() for a in self.args],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PredicateNode:
        return cls(
            operator=data["operator"],
            target=data["target"],
            value=data.get("value"),
            args=tuple(cls.from_dict(a) for a in data.get("args", [])),
        )


@dataclass(frozen=True)
class QueryStep:
    """Immutable single step in a query AST chain."""

    step_type: StepType
    target_type: str = ""
    edge_type: str = ""
    direction: str = "OUTGOING"  # OUTGOING, INCOMING, BOTH
    predicate: PredicateNode | None = None
    limit: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "step_type": self.step_type.value,
            "target_type": self.target_type,
            "edge_type": self.edge_type,
            "direction": self.direction,
            "predicate": self.predicate.to_dict() if self.predicate else None,
            "limit": self.limit,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> QueryStep:
        return cls(
            step_type=StepType(data["step_type"]),
            target_type=data.get("target_type", ""),
            edge_type=data.get("edge_type", ""),
            direction=data.get("direction", "OUTGOING"),
            predicate=PredicateNode.from_dict(data["predicate"]) if data.get("predicate") else None,
            limit=data.get("limit", 0),
        )


@dataclass(frozen=True)
class QueryNode:
    """Immutable Query AST container."""

    target_label: str
    steps: tuple[QueryStep, ...] = field(default_factory=tuple)
    projection_fields: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "target_label": self.target_label,
            "steps": [s.to_dict() for s in self.steps],
            "projection_fields": list(self.projection_fields),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> QueryNode:
        return cls(
            target_label=data["target_label"],
            steps=tuple(QueryStep.from_dict(s) for s in data.get("steps", [])),
            projection_fields=tuple(data.get("projection_fields", [])),
        )

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str) -> QueryNode:
        return cls.from_dict(json.loads(json_str))


@dataclass(frozen=True)
class ExecutionPlanNode:
    """Immutable Execution Plan node generated by QueryPlanner."""

    op_type: str  # INDEX_LOOKUP, SCAN, FILTER, TRAVERSE, PROJECTION
    cost: float = 1.0
    params: dict[str, Any] = field(default_factory=dict)
    children: tuple[ExecutionPlanNode, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "op_type": self.op_type,
            "cost": self.cost,
            "params": self.params,
            "children": [c.to_dict() for c in self.children],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ExecutionPlanNode:
        return cls(
            op_type=data["op_type"],
            cost=data.get("cost", 1.0),
            params=data.get("params", {}),
            children=tuple(cls.from_dict(c) for c in data.get("children", [])),
        )
